name: filter
description: A flutter plugin to apply images filters natively.
version: 0.0.3
homepage: https://github.com/Iampato/Image-Filters

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.filter
        pluginClass: FilterPlugin
      